name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  actions: read
  checks: write
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - id: setup
      name: setup
      uses: classroom-resources/autograding-command-grader@v1
      with:
        command: venv/bin/python -m pip install pytest flake8
          pep8-naming flake8-docstrings pandas numpy
        max-score: null
        setup-command: python3 -m venv venv
        test-name: setup
        timeout: 1
    - id: exercise-8-2
      name: exercise-8-2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        command: venv/bin/python -m pytest tests/test_mfe.py
        max-score: 2
        setup-command: ''
        test-name: exercise-8-2
        timeout: 1
    - id: flake8
      name: flake8
      uses: classroom-resources/autograding-command-grader@v1
      with:
        command: venv/bin/python -m flake8 --extend-exclude=venv
        max-score: 1
        setup-command: ''
        test-name: flake8
        timeout: 1
    - env:
        EXERCISE-8-2_RESULTS: ${{steps.exercise-8-2.outputs.result}}
        FLAKE8_RESULTS: ${{steps.flake8.outputs.result}}
        SETUP_RESULTS: ${{steps.setup.outputs.result}}
      name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      with:
        runners: setup, exercise-8-2, flake8
